spring.datasource.url=jdbc:postgresql://localhost:5432/tron_21_06?currentSchema=metadata
spring.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/tron_21_06?currentSchema=metadata

spring.jpa.properties.hibernate.default_schema=metadata



spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=tron
spring.datasource.password=tronpw
